
CANNT_LOGIN_ACCOUNT = 3000  # 不能登录帐号


WRONG_INVITE_CODE = 1000  # 错误的邀请码，没有找到对应的邀请者
NOT_FOUND_INVITEES = 1001  # 没有受邀者
ALREADY_TAKE_REWARD = 1002  # 已经领取过奖励了
CREATE_FIRST_STALL = 1003  # 第一个摊位没有创建
NOT_FOUND_INVITE_ACTIVITY = 1004  # 错误的领取参数
ALREADY_TAKE_INVITE_ACTIVITY_REWARD = 1005  # 邀请活动奖励已领取
INVITE_FRIEND_IS_NOT_ENOUGH = 1006  # 邀请的好友数不够
INVITE_STALL_CONDITION_NOT_MATCH = 1007  # 摊位条件不满足
WRONG_INIT_IN_COME = 1008  # 摊位初始收益区间数值不合法



ROOM_NOT_FOUND_KEY = 2000
ROOM_FULL_PLAYER = 2001